# Generated by Django 3.2.9 on 2021-12-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20211215_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.CharField(blank=True, choices=[('_blank', 'открыть на новой странице')], max_length=20, null=True, verbose_name='Поведение'),
        ),
    ]
