# Generated by Django 3.2.9 on 2021-12-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_menu_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=255, verbose_name='ссылка'),
        ),
    ]
