# Generated by Django 3.2.9 on 2021-12-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('seo_name', models.CharField(max_length=255, verbose_name='Название на ссылке')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цына')),
                ('featured', models.BooleanField(default=False, verbose_name='показаным')),
                ('new', models.BooleanField(default=False, verbose_name='новый')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.category', verbose_name='Категория')),
                ('thumbnails', models.ManyToManyField(blank=True, null=True, to='business.File', verbose_name='thumbnails')),
            ],
        ),
    ]
