# Generated by Django 3.2.9 on 2021-12-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_file_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Казахский'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Казахский'),
        ),
        migrations.AddField(
            model_name='product',
            name='ame_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Казахский'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='содержание Казахский'),
        ),
    ]
