# Generated by Django 3.2.9 on 2021-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20211215_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seo_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnails',
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
