# Generated by Django 3.2.9 on 2021-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20211215_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ame_kk',
            new_name='name_kk',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
