# Generated by Django 3.2.9 on 2021-12-16 05:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[('product', 'Продукт'), ('page', 'Страница')], default='product', max_length=255, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.CharField(choices=[('top', 'верхнее меню заголовка'), ('bottom', 'нижнее меню')], default='product', max_length=255, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Заголовок_kk')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='содержание')),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='содержание Казахский')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.menu')),
            ],
        ),
    ]
