# Generated by Django 3.2.9 on 2021-12-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20211216_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.page', verbose_name='на страницу'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок_kk'),
        ),
    ]
