# Generated by Django 3.2.9 on 2021-12-25 09:34
import topnotchdev
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20211216_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=topnotchdev.files_widget.fields.ImagesField(blank=True, null=True),
        ),
    ]
